twitch:
  client_id: "cxlvasdfualsdm"
  client_secret: "dfalsdfusdofoiiulx"
  channels:
    Rlly:
      backlog: False
      chapters: "titles"
      quality: "best"
      timezone: "America/Cambridge_Bay"
      youtube_param:
        title: "%C VOD %m/%d/%Y"
        description: "Follow %C at https://twitch.tv/%C to watch live!"
        categoryId: "20"
        privacy: "private"
        playlistId: "PLRV-ewmAAe9rHVKkhr3hz3eSzME__G0si"
        tags:
          - "GTA RP"
          - "nopixel"
  webhook:
    host: "mysupersecretdomain.com"
    local: "192.168.1.2"
    port: 42069
    ssl_port: 42070
    ssl_cert: "server.pem"
youtube:
  upload: True
  json: "secrets.json"
download:
  keep: False
  directory: ""
