twitch:
  client_id: cxlvasdfualsdm
  client_secret: dfalsdfusdofoiiulx
  channels:
    Rlly:
      backlog: false
      chapters: titles
      quality: best
      timezone: America/Cambridge_Bay
      youtube_param:
        title: '%C VOD %m/%d/%Y'
        description: Follow %C at https://twitch.tv/%C to watch live!
        categoryId: '20'
        playlistId: PLRV-ewmAAe9rHVKkhr3hz3eSzME__G0si
        privacy: private
        tags:
        - GTA RP
        - nopixel
youtube:
  upload: true
  json: secrets.json
  sort: true
download:
  keep: false
  directory: ''
  quota_pause: true